version : '3'
services:
  mysql:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: core
    ports:
      - "3306:3306"
    volumes:
      - "./script/1_schema.sql:/docker-entrypoint-initdb.d/1.sql"